apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT }}
            - name: JWT_SECRET
              value: {{ .Values.env.JWT_SECRET }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.env.ADMIN_PASSWORD }}
            - name: LOCALSTACK_HOST
              value: {{ .Values.env.LOCALSTACK_HOST }}
            - name: LOCALSTACK_PORT
              value: {{ .Values.env.LOCALSTACK_PORT }}
          ports:
            - containerPort: 3000
