services:
  restaurants_db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurants_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: s3,dynamodb,cloudwatch
    ports:
      - "4566:4566"

  node_app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run setup"
    depends_on:
      restaurants_db:
        condition: service_healthy
      localstack:
        condition: service_started
    environment:
      DB_USER: postgres
      DB_HOST: restaurants_db
      DB_NAME: restaurants_test
      DB_PASSWORD: postgres
      DB_PORT: 5432
      JWT_SECRET: your-secret-key-here
      ADMIN_PASSWORD: your-admin-password