version: '3.8'

services:
  restaurants_db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurants
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: s3,dynamodb,cloudwatch
    ports:
      - "4566:4566"

  node_app:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run setup"
    depends_on:
      restaurants_db:
        condition: service_healthy
      localstack:
        condition: service_started
    environment:
      DB_USER: user
      DB_HOST: restaurants_db
      DB_NAME: restaurants
      DB_PASSWORD: password
      DB_PORT: 5432
      JWT_SECRET: test-secret
      ADMIN_PASSWORD: test-password