apiVersion: v1
kind: Service
metadata:
  name: express-app
  namespace: example
spec:
  selector:
    app: express-app
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: my-docker-username/my-app:latest
          env:
            - name: DB_USER
              value: "postgres"
            - name: DB_HOST
              value: "postgres"
            - name: DB_NAME
              value: "restaurants"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: JWT_SECRET
              value: "your-secret-key-here"
            - name: ADMIN_PASSWORD
              value: "your-admin-password"
            - name: LOCALSTACK_HOST
              value: "localstack"
            - name: LOCALSTACK_PORT
              value: "4566"
          ports:
            - containerPort: 3000