name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restaurants
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install Docker Compose
        run: sudo apt-get install docker-compose
      
      - name: Set up Docker Compose
        run: docker-compose up -d
      
      - name: Run tests
        run: docker-compose run node_app npm test
        env:
          NODE_ENV: test
          DB_USER: user
          DB_HOST: restaurants_db
          DB_NAME: restaurants
          DB_PASSWORD: password
          DB_PORT: 5432
          JWT_SECRET: test-secret
          ADMIN_PASSWORD: test-password
